package com.joe.joe;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;

@SpringBootApplication
public class JoeApplication {
	@Autowired
	private EmailSenderService service;
	

	public static void main(String[] args) {
		//System.out.println("Hello Java");  
		SpringApplication.run(JoeApplication.class, args);
	}
		@EventListener(ApplicationReadyEvent.class)
		public void triggerMail() {
			service.sendSimpleEmail("joseph.kimanzi@ncbagroup.com",
					"Spring Boot Mail", 
					 "Hello,This email has been generated by spring boot");
			service.sendSimpleEmail("danson.mwema@ncbagroup.com",
					"Spring Boot Mail", 
					 "Hello,This email has been generated by spring boot");
		/*service.sendSimpleEmail("joekimanzi1998@gmail.com",
				"Spring Boot Mail", 
				 "Hello,This is a spring boot mail");*/
		/*service.sendSimpleEmail("joekim363@gmail.com",
				"Spring Boot Mail", 
				 "Hello,This is a spring boot mail");*/
		}
			
		
	

}
